eureka:
  client:
    service-url:
      defaultZone: http://chenyx:chenyx135@springcloud-eureka-server:8080/eureka/,http://jake:jake135@springcloud-eureka-server02:8084/eureka/,http://xiaopei:xiaopei135@springcloud-eureka-server01:8083/eureka/
    healthcheck:
      enabled: true #需要引入actuate的jar
      # 心跳检测检测与续约时间
      # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
      # 配置说明
      #　　lease-renewal-interval-in-seconds 每间隔10s，向服务端发送一次心跳，证明自己依然”存活“
      #　　lease-expiration-duration-in-seconds  告诉服务端，如果我20s之内没有给你发心跳，就代表我“死”了，将我踢出掉
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}-hystrix:${server.port} #默认为application-name:port
    prefer-ip-address: true
spring:
  application:
    name: springcloud-eureka-provider-hystrix
server:
  port: 8088
  servlet:
    context-path: /springcloud-eureka-provider-hystrix