spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenyx1/springcloud-config-repo.git #github地址
          username: chenyx1
          password: Xiaopei135
          basedir: D:\study\git\springcloud-config-repo