server:
  port: 8094
spring:
  application:
    name: springcloud-zk-zuul
  cloud:
    zookeeper:
      connect-string: 192.168.80.129:2181 #连接zk注册中心,集群有“，”分割
      discovery:
        enabled: true  #启动zk服务发现

zuul:
  routes:
    spring-zk-consumer:
      serviceId: spring-zk-consumer
      path: /zkConsumer/** #虚拟路径

    springcloud-zk-provider-hystrix:
      serviceId: springcloud-zk-provider-hystrix
      path: /zkProviderHystrix/**
  ignored-services: "*"    #忽略真路径采用set存储配。当需要忽略所有的服务真实路径时，采用“*”
  prefix: /zk-zuul #定义统一前缀


