server:
  port: 8082
  servlet:
    context-path: /springcloud-eureka-comsumer
server-info:
  ip: 127.0.0.1
  server-name: springcloud-eureka-provider
  url: http://${server-info.ip}:${server-info.port}/${server-info.server-name}
  port: 8081




